;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
;; with 1 and 2, the first 10 terms will be:

;;      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
;; the sum of the even-valued terms.

(define fibs-up-to
  (lambda (x y)
    (cond
     ((>= (car x) y) (cdr x))
     (else
      (fibs-up-to (next-fib x) y)))))

(define next-fib
  (lambda (x)
    (cons (+ (first x) (second x)) x)))

(next-fib '(2 1))

(foldl + 0 (filter even? (fibs-up-to '(2 1) 4000000)))
